/* Magic Hat Adventures — framework-free, static-file RPG. */
(async function(){
'use strict';
const D=MHA.DATA,A=MHA.Assets,S=MHA.State,$=id=>document.getElementById(id);
const world=$('world'),ctx=world.getContext('2d'),overlay=$('overlay');
let gameState=S.load(),player={...gameState.playerPosition},follower={x:player.x-65,y:player.y},trail=[{...follower},{...player}],keys=new Set(),nearest=null,mode='loading',quiz=null,lastTime=0,lastSave=0,toastTimer,focusBefore=null;
const audioFiles={}; // Optional overrides: audioFiles["It's under the table."] = 'assets/audio/under-table.mp3';
let activeAudio=null;
const blockHint=document.createElement('div');blockHint.id='blockedHint';blockHint.setAttribute('role','status');blockHint.setAttribute('aria-live','polite');$('stage').append(blockHint);
let blockHintTimer,lastBlock=null,blockCooldown=0;
function hintBlocked(kind){if(!kind||kind==='npc'){lastBlock=null;return}const now=performance.now();if(kind!==lastBlock&&now>=blockCooldown){blockHint.textContent=kind==='railing'?'Can’t go behind the railing!':kind==='furniture'?'Something is blocking the way!':'Can’t go there!';blockHint.style.top=player.y<D.height/2?'76%':'10%';blockHint.classList.add('visible');clearTimeout(blockHintTimer);blockHintTimer=setTimeout(()=>blockHint.classList.remove('visible'),1400);blockCooldown=now+1500}lastBlock=kind}

const img=(key,cls='')=>`<img class="${cls}" src="${A.urls[key]}" alt="${key.replaceAll('_',' ')}">`;
const button=(label,action,cls='')=>{const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=action;return b};
const phrase=q=>`It’s ${q.prep} the ${q.noun}.`;
function persist(){gameState.playerPosition={...player};const ok=S.save(gameState);$('saveStatus').textContent=ok?'Progress saves on this device':'Saving unavailable — keep this tab open';hud()}
function hud(){const n=gameState.gemsCollected.length;$('gemCount').textContent=`GEMS: ${n} / 8`;$('mapCount').textContent=`MAP: ${gameState.mapPieces} / 8`;$('soundButton').textContent='Sound: '+(gameState.soundEnabled?'ON':'OFF');$('soundButton').setAttribute('aria-pressed',gameState.soundEnabled);$('missionHint').textContent=gameState.gameCompleted?'Adventure complete!':gameState.finalMissionUnlocked?'Map complete! Return to the Captain.':Object.keys(gameState.unlockedChests).some(i=>!gameState.openedChests[i])?'A chest is unlocked! Visit the Treasure Room.':'Meet the crew. Find the eight gems.'}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.add('visible');toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000)}
function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();if(activeAudio){activeAudio.pause();activeAudio=null}}
function speak(text){stopSpeech();if(!gameState.soundEnabled){toast('Sound is off. Turn sound on to listen.');return false}
 const file=audioFiles[text.replaceAll('’',"'")];if(file){activeAudio=new Audio(file);activeAudio.play().catch(()=>toast('Audio could not play. Try Listen again.'));return true}
 if(!('speechSynthesis'in window)){toast('Speech is unavailable. Use Show words for reading practice.');return false}
 const u=new SpeechSynthesisUtterance(text.replaceAll('’',"'"));u.lang='en-US';u.rate=.78;u.pitch=1.05;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='en-US')||voices.find(v=>v.lang.startsWith('en'))||null;u.onerror=e=>{if(e.error!=='interrupted'&&e.error!=='canceled')toast('Voice unavailable. Try Listen again or Show words.')};speechSynthesis.speak(u);return true}
function show(html,newMode='dialogue',style=''){keys.clear();clearTimeout(blockHintTimer);blockHint.classList.remove('visible');lastBlock=null;stopSpeech();clearTimeout(toastTimer);$('toast').classList.remove('visible');focusBefore=document.activeElement;overlay.hidden=false;overlay.className=style;overlay.innerHTML=html;mode=newMode;overlay.focus();requestAnimationFrame(()=>overlay.querySelector('button')?.focus());$('proximity').hidden=true;$('interactButton').disabled=true}
function close(){keys.clear();stopSpeech();overlay.hidden=true;overlay.innerHTML='';mode='world';quiz=null;world.focus();persist()}
function dialogue(person,text,actions=[['Back to the ship',close]]){show(`<div class="dialogue">${img(person.asset,'portrait')}<div><h2>${person.name}</h2><p>${text}</p><div class="actions" id="dialogueActions"></div></div></div>`);actions.forEach(([name,fn],i)=>$('dialogueActions').append(button(name,fn,i===actions.length-1?'primary':'')))}
function cutscene(lines,onFinish,ending=false){let step=0;function next(){if(step>=lines.length){onFinish();return}const line=lines[step++];show(`<div class="scene-card ${line.glow?'glow':''}"><div class="eyebrow">MAGIC HAT ADVENTURES</div><h1>${line.title||'Where’s the Treasure?'}</h1>${img(line.asset||'magic_hat_girl','scene-portrait')}<h2>${line.name||'Magic Hat Girl'}</h2><p>${line.text}</p><div id="sceneActions"></div></div>`,ending?'ending':'opening',line.world?'':'cutscene');$('sceneActions').append(button(line.button||'Next',next,'primary'))}next()}
// Suggested teaching order only; original mission/chest IDs and access stay unchanged.
const routeOrder=[1,0,2,3,4,5,6,7];
function playOrder(){
 const next=routeOrder.find(i=>!gameState.openedChests[i]);
 const labels=['位置詞辨認','物品辨認','選位置詞','選物品','聽力','拖曳位置','排列句子','綜合挑戰'];
 const nextText=next===undefined?(gameState.gameCompleted?'全部完成！': '返回 Captain，挑戰最後一題！'):(gameState.completedChallenges[D.missions[next].id]?`先到寶藏室，開啟 ${next+1} 號寶箱。`:`建議先找：${D.missions[next].name}`);
 show(`<div class="panel route-panel"><div class="panel-top"><h2>建議通關順序 · Easy → Hard</h2><button id="closeRoute" class="close" aria-label="Close play order">×</button></div><p class="small-help">由簡單到困難，跟著圖片與箭頭找船員！</p><ol class="route-list">${routeOrder.map((i,step)=>{const m=D.missions[i],done=gameState.openedChests[i];return `<li class="route-step ${done?'route-done':''} ${i===next?'route-next':''}"><span class="route-number">${step+1}</span>${img(m.asset)}<strong>${m.name}</strong><span>${labels[i]}</span><small>${done?'✓ 已收集':gameState.completedChallenges[m.id]?`開啟 ${i+1} 號寶箱`:i===next?'從這裡繼續':''}</small></li>`}).join('')}</ol><div class="route-final"><span aria-hidden="true">↓</span>${img('captain')}<div><strong>9 · Captain</strong><p>收齊 8 顆寶石 → 最終尋寶</p></div></div><p class="route-guidance">${nextText}</p><p class="small-help">每次完成練習，再走到寶藏室開箱。這是建議順序，也可以自由探索。</p><div class="actions"><button id="followRoute" class="primary">LET’S GO!</button></div></div>`,'route');
 $('closeRoute').onclick=close;$('followRoute').onclick=close;
}
function opening(){cutscene([
 {text:'Are you ready for an adventure?',button:'YES!'},
 {text:'The Magic Hat is shining!',glow:true,button:'To Pirate World!'},
 {text:'Wow! We’re on a pirate ship!\nWe’re in Pirate World!',world:true},
 {asset:'captain',name:'Captain',text:'Ahoy! I need your help!\nOur treasure is missing!',world:true},
 {asset:'captain',name:'Captain',text:'Can you help us find it?',world:true},
 {text:'Let’s help them!',world:true},
 {asset:'captain',name:'Captain',text:'Find the eight gems.\nComplete the treasure map.\nAnd find our treasure!',world:true},
 {title:'NEW MISSION',text:'WHERE’S THE TREASURE?',button:'MISSION START!',world:true}
 ],()=>{gameState.openingCompleted=true;persist();playOrder()})}
function ending(){cutscene([
 {asset:'final_treasure',name:'Captain',title:'TREASURE FOUND!',text:'You found our treasure!\nThank you!',world:true},
 {asset:'crew',name:'Crew',text:'Hooray!',world:true},
 {asset:'parrot',name:'Parrot',text:'Squawk! Great job!',world:true},
 {text:'We did it!\nThanks for coming with me!'},
 {text:'The Magic Hat is shining again!',glow:true}
 ],()=>{gameState.gameCompleted=true;persist();completeScreen()},true)}
function completeScreen(){show(`<div class="scene-card"><div class="eyebrow">MAGIC HAT ADVENTURES</div><h1>ADVENTURE COMPLETE!</h1>${img('final_treasure','scene-portrait')}<p>GEMS: 8 / 8 &nbsp; MAP: 8 / 8</p><div class="actions" id="finishActions"></div></div>`,'complete','cutscene');$('finishActions').append(button('Explore again',close),button('PLAY AGAIN',restart,'primary'))}
function restart(){const oldNodes=[...overlay.childNodes],oldMode=mode,oldStyle=overlay.className,wasHidden=overlay.hidden;show('<div class="panel confirm"><h1>Restart the adventure?</h1><p>Your progress will be cleared.</p><div class="actions" id="restartActions"></div></div>','confirm');$('restartActions').append(button('Cancel',()=>{overlay.replaceChildren(...oldNodes);overlay.className=oldStyle;overlay.hidden=wasHidden;mode=oldMode;keys.clear();if(wasHidden)world.focus();else overlay.querySelector('button')?.focus()}),button('Restart',()=>{stopSpeech();gameState=S.fresh();player={...gameState.playerPosition};follower={x:player.x-65,y:player.y};trail=[{...follower},{...player}];quiz=null;persist();opening()},'primary'))}
function inPolygon(x,y){let inside=false;const p=D.hull;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside}return inside}
function collisionKind(x,y,includeNPC=true){const r=11;if(![[x-r,y],[x+r,y],[x,y-r],[x,y+r]].every(([a,b])=>inPolygon(a,b)))return x>608&&x<1098&&y<220?'railing':'wall';
 const wall=D.walls.find(([a,b,w,h])=>x+r>a&&x-r<a+w&&y+r>b&&y-r<b+h);if(wall)return wall[4]||'wall';
 if(D.chests.some(c=>Math.abs(c.x-x)<30&&Math.abs(c.y-y)<19))return 'furniture';
 if(includeNPC&&[D.captain,...D.missions].some(n=>Math.hypot(n.x-x,n.y-y)<27))return 'npc';return null}
function blocked(x,y,includeNPC=true){return !!collisionKind(x,y,includeNPC)}
function companionStart(){for(const [dx,dy]of [[-64,0],[64,0],[0,64],[0,-64],[-45,45],[45,45]])if([.25,.5,.75,1].every(t=>!blocked(player.x+dx*t,player.y+dy*t,false)))return{x:player.x+dx,y:player.y+dy};return{...player}}
function move(dx,dy,dt){if(!dx&&!dy){lastBlock=null;return}const length=Math.hypot(dx,dy),dist=dt*178,steps=Math.ceil(dist/5);let hit=null;for(let i=0;i<steps;i++){const nx=player.x+dx/length*dist/steps,ny=player.y+dy/length*dist/steps;const bx=dx?collisionKind(nx,player.y):null;if(!bx)player.x=nx;else if(!hit||hit==='npc')hit=bx;const by=dy?collisionKind(player.x,ny):null;if(!by)player.y=ny;else if(!hit||hit==='npc')hit=by}hintBlocked(hit);
 const last=trail[trail.length-1];if(Math.hypot(last.x-player.x,last.y-player.y)>5)trail.push({...player});let acc=0;for(let i=trail.length-1;i>0;i--){const p=trail[i],q=trail[i-1],d=Math.hypot(p.x-q.x,p.y-q.y);if(acc+d>=66){const t=(66-acc)/d;follower={x:p.x+(q.x-p.x)*t,y:p.y+(q.y-p.y)*t};if(i>1)trail.splice(0,i-1);break}acc+=d}if(Math.hypot(follower.x-player.x,follower.y-player.y)>170){follower={...player};trail=[{...player}]}}
function nearestEntity(){const candidates=[D.captain,...D.missions,...D.chests,D.mapDisplay];return candidates.filter(n=>{
  const distance=Math.hypot(n.x-player.x,n.y-player.y);if(distance>(n.id==='map'?105:73))return false;
  // Ignore target furniture but reject interactions across walls by sampling sight line.
  for(let t=.15;t<.85;t+=.15){const x=player.x+(n.x-player.x)*t,y=player.y+(n.y-player.y)*t;if(D.walls.some(([a,b,w,h])=>x>a&&x<a+w&&y>b&&y<b+h&&!(n.id==='map'&&a===781)))return false}return true;
 }).sort((a,b)=>Math.hypot(a.x-player.x,a.y-player.y)-Math.hypot(b.x-player.x,b.y-player.y))[0]||null}
function interaction(){if(mode!=='world'||!nearest)return;const n=nearest;if(n.id==='captain'){if(gameState.finalMissionCompleted){dialogue(n,'You found our treasure!\nThank you!');return}if(gameState.finalMissionUnlocked){dialogue(n,'You found the treasure map!\nNow find the treasure!',[['Later',close],['Final Mission',()=>startQuiz({id:'final',name:'Captain',asset:'captain',count:1,type:'final',focus:'Final mission'})]]);return}dialogue(n,`Keep looking for the gems!\nYou have ${gameState.gemsCollected.length} of 8 gems.\nTalk to my crew. They may have clues!`);return}
 if(n.id==='map'){inventory();return}if(n.id.startsWith('chest')){chest(n.index);return}
 const i=D.missions.indexOf(n);if(gameState.completedChallenges[n.id]){dialogue(n,gameState.openedChests[i]?'Great job! You found my gem.':'Your chest is unlocked!\nGo to the Treasure Room!',[['Back to the ship',close],['Practice again',()=>startQuiz(n)]]);return}dialogue(n,n.intro,[['Later',close],['Start Challenge',()=>startQuiz(n)]])}
function chest(i){if(!gameState.unlockedChests[i]){dialogue(D.captain,`This chest is locked.\nTalk to ${D.missions[i].name} first!`);return}if(gameState.openedChests[i]){toast('You already collected this gem.');return}if(!S.openChest(gameState,i))return;persist();show(`<div class="panel confirm"><div class="eyebrow">TREASURE CHEST OPENED!</div><div class="reward">${img(D.gems[i])}<p>You found ${i===2||i===4||i===5?'an':'a'} ${D.gemNames[i]}!<br><br>GEM +1<br>MAP PIECE +1</p></div><div class="actions" id="rewardActions"></div></div>`,'reward');$('rewardActions').append(button('Continue',()=>{if(gameState.treasureMapComplete){dialogue({name:'Magic Hat Girl',asset:'magic_hat_girl'},'MAP COMPLETE!\nWe found the whole map!\nLet’s go back to the Captain!',[['See the map',inventory],['Back to the ship',close]])}else close()},'primary'))}
function drawMap(c){const g=c.getContext('2d'),im=A.images.map;c.width=640;c.height=426;g.fillStyle='#153341';g.fillRect(0,0,640,426);g.imageSmoothingEnabled=false;for(let i=0;i<8;i++){const x=(i%4)*160,y=Math.floor(i/4)*213;if(gameState.openedChests[i])g.drawImage(im,(i%4)*im.width/4,Math.floor(i/4)*im.height/2,im.width/4,im.height/2,x,y,160,213);else{g.fillStyle='#294853';g.fillRect(x+2,y+2,156,209);g.fillStyle='#799499';g.font='bold 28px Arial';g.textAlign='center';g.fillText('?',x+80,y+112)}}}
function inventory(){show(`<div class="panel"><div class="panel-top"><h2>${gameState.treasureMapComplete?'MAP COMPLETE!':'Your treasure map'}</h2><button class="close" id="closeMap" aria-label="Close map">×</button></div><div class="inventory-grid"><div><canvas id="mapPreview" class="map-preview" aria-label="Treasure map with ${gameState.mapPieces} of 8 pieces revealed"></canvas><p class="small-help">MAP: ${gameState.mapPieces} / 8 · Open chests to find pieces.</p></div><div><div class="gem-list">${D.gems.map((g,i)=>`<div class="gem-item ${gameState.openedChests[i]?'':'missing'}">${gameState.openedChests[i]?img('gem_'+g):'<div style="height:48px">?</div>'}<div>${D.gemNames[i]}</div></div>`).join('')}</div><div class="crew-list">${D.missions.map((m,i)=>`<div>${m.name}<br><span>${gameState.openedChests[i]?'Gem collected':gameState.unlockedChests[i]?'Chest unlocked':'Meet the crew'}</span></div>`).join('')}</div></div></div></div>`,'inventory');drawMap($('mapPreview'));$('closeMap').onclick=close}
function drawSprite(key,x,y,h,flip=false){const im=A.images[key];if(!im)return;const w=h*im.width/im.height;ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(im,-w/2,-h,w,h);ctx.restore()}
function renderWorld(t){ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,D.width,D.height);ctx.drawImage(A.images.ship,0,0,D.width,D.height);
 // A traversable storage doorway uses an existing deck-floor crop, never a redrawn map.
 ctx.drawImage(A.images.ship,435,520,60,58,489,382,62,58);
 // Display only obtained map sections on the official map-room table.
 const map=A.images.map;for(let i=0;i<8;i++)if(gameState.openedChests[i])ctx.drawImage(map,i%4*map.width/4,Math.floor(i/4)*map.height/2,map.width/4,map.height/2,792+(i%4)*27,627+Math.floor(i/4)*24,27,24);
 const entities=[{...D.captain,h:91},...D.missions.map(n=>({...n,h:n.id==='parrot'?69:82})),...D.chests.map(n=>({...n,asset:gameState.openedChests[n.index]?D.gems[n.index]:'treasure_chest',h:66})),{...follower,asset:'magic_hat_girl',h:86,id:'follower'},{...player,asset:'player',h:78,id:'player'}].sort((a,b)=>a.y-b.y);
 entities.forEach(n=>{if(n.id==='player'){ctx.strokeStyle='#fff5a7';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(n.x,n.y+2,20,7,0,0,Math.PI*2);ctx.stroke()}drawSprite(n.asset,n.x,n.y,n.h);
 if(n.id.startsWith('chest')){const i=n.index;ctx.fillStyle=gameState.openedChests[i]?'#8ce6bf':gameState.unlockedChests[i]?'#ffe082':'#e2c896';ctx.font='bold 16px Arial';ctx.textAlign='center';ctx.fillText(gameState.openedChests[i]?'✓':String(i+1),n.x,n.y+19);if(gameState.unlockedChests[i]&&!gameState.openedChests[i]){ctx.strokeStyle='#ffeb85';ctx.lineWidth=3;ctx.strokeRect(n.x-27,n.y-65,54,68)}}
 else if(n.id!=='player'&&n.id!=='follower'){const i=D.missions.findIndex(m=>m.id===n.id),finished=i>=0&&gameState.completedChallenges[n.id];ctx.fillStyle=finished?'#a1f2c9':'#fff0a2';ctx.font='bold 25px Arial';ctx.textAlign='center';ctx.strokeStyle='#143543';ctx.lineWidth=5;const marker=finished?'✓':'!';ctx.strokeText(marker,n.x,n.y-n.h-9);ctx.fillText(marker,n.x,n.y-n.h-9)}
 });
 if(mode==='world'){nearest=nearestEntity();const prompt=$('proximity'),b=$('interactButton');prompt.hidden=!nearest;b.disabled=!nearest;if(nearest){const isChest=nearest.id.startsWith('chest'),word=isChest?'Open':nearest.id==='map'?'View map':'Talk';prompt.textContent=`${nearest.name|| (isChest?'Chest '+(nearest.index+1):'Treasure map')} · Press E to ${word}`;b.textContent=word.toUpperCase()}}
}
function frame(time){const dt=Math.min((time-lastTime)/1000||0,.04);lastTime=time;if(mode==='world'){const dx=(keys.has('right')?1:0)-(keys.has('left')?1:0),dy=(keys.has('down')?1:0)-(keys.has('up')?1:0);move(dx,dy,dt);if(time-lastSave>1500){persist();lastSave=time}}if(A.images.ship)renderWorld(time);requestAnimationFrame(frame)}
// Spatial picture geometry is shared by recognition, listening, dragging and final tasks.
function positions(noun){return{in:{x:300,y:143},on:{x:300,y:65},under:{x:300,y:233},by:{x:476,y:191}}}
function scene(canvas,q,subject='gem_ruby',dragPosition=null,showZones=false){canvas.width=600;canvas.height=280;const g=canvas.getContext('2d');g.imageSmoothingEnabled=false;g.fillStyle='#dceee9';g.fillRect(0,0,600,280);g.fillStyle='#b8d9d0';g.fillRect(0,246,600,34);const o=A.images[q.noun],figure=A.images[subject];const wide=['table','desk'].includes(q.noun),w=wide?250:170,h=wide?160:170,x=300-w/2,y=88;
 g.drawImage(o,x,y,w,h);const p=dragPosition||positions(q.noun)[q.prep],size=subject==='parrot'?72:59,fw=size*figure.width/figure.height;
 // A small cutaway view makes "in" legible even though the official box is closed.
 // The official object remains the surrounding/front image; this is a teaching overlay.
 if(q.prep==='in'&&!dragPosition){g.fillStyle='#254a50';g.fillRect(x+12,y+14,w-24,h*.32)}
 if(showZones){g.strokeStyle='#688f91';g.setLineDash([5,5]);g.lineWidth=2;for(const pos of Object.values(positions(q.noun)))g.strokeRect(pos.x-34,pos.y-30,68,60);g.setLineDash([])}
 g.drawImage(figure,p.x-fw/2,p.y-size/2,fw,size);
 if(!dragPosition&&q.prep==='in'){// Front of box/bag overlaps the lower gem: clear, meaningful "in".
  const cut=.40;g.drawImage(o,0,o.height*cut,o.width,o.height*(1-cut),x,y+h*cut,w,h*(1-cut));
 }
}
function startQuiz(m){quiz={mission:m,questions:MHA.makeQuestions(m),index:0,solved:false,prep:null,noun:null,words:[],order:[],drag:null,listenOptions:null};renderQuiz()}
function renderQuiz(){const z=quiz,m=z.mission,q=z.questions[z.index];z.solved=false;z.prep=null;z.noun=null;z.words=[];z.drag={x:83,y:212};
 show(`<div class="panel"><div class="panel-top">${img(m.asset,'portrait')}<div><h2>${m.name} · ${m.focus}</h2><span class="progress">${z.index+1} / ${m.count}</span></div><button class="close" id="quitQuiz" aria-label="Leave challenge">×</button></div><h1 class="question" id="question"></h1><div id="quizBody"></div><div class="feedback" id="feedback" role="status"></div><div class="actions quiz-actions" id="quizActions"></div></div>`,'quiz');
 $('quitQuiz').onclick=()=>dialogue(m,'Leave this challenge?\nYou can try again any time.',[['Keep playing',renderQuiz],['Leave',close]]);
 const body=$('quizBody'),question=$('question'),actions=$('quizActions');
 if(m.type==='vocab'){question.textContent=`Find the ${q.noun}!`;body.innerHTML='<div class="object-choices" id="objectChoices"></div>';MHA.shuffle(D.nouns).forEach(n=>{const b=button('',()=>answer(n===q.noun));b.className='object-choice';b.setAttribute('aria-label',n);b.dataset.choice=n;b.innerHTML=img(n);$('objectChoices').append(b)})}
 else if(m.type==='listen'){question.textContent='Listen. Choose the matching picture.';const options=MHA.shuffle([q,...MHA.shuffle(D.validPairs.filter(p=>p.prep!==q.prep||p.noun!==q.noun)).slice(0,2)]);z.listenOptions=options;body.innerHTML='<div class="actions quiz-actions" id="listenActions"></div><div class="listen-choices" id="listenChoices"></div>';$('listenActions').append(button('LISTEN AGAIN',()=>speak(phrase(q)),'primary'),button('Show words',()=>{toast(phrase(q))}));options.forEach((p,i)=>{const b=button('',()=>answer(p.prep===q.prep&&p.noun===q.noun));b.setAttribute('aria-label','Picture '+(i+1));b.dataset.picture=i;const c=document.createElement('canvas');b.append(c);scene(c,p);$('listenChoices').append(b)});speak(phrase(q))}
 else {const type=m.type;question.textContent=type==='prep'?'Where’s the parrot?':type==='drag'?`Put the treasure ${q.prep} the ${q.noun}.`:'Where’s the treasure?';body.innerHTML='<div class="quiz-layout"><div><canvas class="spatial" id="sceneCanvas"></canvas></div><div id="answerArea"></div></div>';const area=$('answerArea');scene($('sceneCanvas'),q,type==='prep'?'parrot':'gem_ruby',type==='drag'?z.drag:null,type==='drag');
 if(['prep','prepSentence','noun'].includes(type)){if(type!=='prep')area.innerHTML=`<div class="question">It’s ${type==='prepSentence'?'___':q.prep} the ${type==='noun'?'___':q.noun}.</div>`;const choices=document.createElement('div');choices.className='choices';MHA.shuffle(type==='noun'?D.nouns:D.prepositions).forEach(v=>{const b=button(v,()=>answer(v===(type==='noun'?q.noun:q.prep)));b.dataset.choice=v;choices.append(b)});area.append(choices)}
 if(type==='drag'){area.innerHTML='<p class="question">Drag the gem.</p><p class="small-help">Move it to the right place.<br>You can also tap the gem, then tap a place.</p>';setupDrag($('sceneCanvas'),q);actions.append(button('CHECK',()=>{const p=positions(q.noun)[q.prep];answer(Math.hypot(z.drag.x-p.x,z.drag.y-p.y)<47)},'primary'))}
 if(type==='sentence'){area.innerHTML='<div class="sentence" id="sentence" aria-label="Your sentence"></div><div class="choices" id="wordCards"></div><p class="small-help">Tap words in order. Tap a chosen word to remove it.</p>';z.order=MHA.shuffle(['It’s',q.prep,'the',q.noun,'.']);wordCards();actions.append(button('Clear',()=>{z.words=[];wordCards()}),button('CHECK',()=>answer(JSON.stringify(z.words)===JSON.stringify(['It’s',q.prep,'the',q.noun,'.'])),'primary'))}
 if(type==='integrated'){area.innerHTML='<p class="small-help">Tap three words in order.</p><div class="sentence orange-sentence" id="builtSentence" aria-label="Your sentence">It’s <span class="orange-slot">___</span> <span class="orange-slot">___</span> <span class="orange-slot">___</span>.</div><div class="choices" id="orangeWords"></div>';const bank=MHA.shuffle([q.prep,'the',q.noun,...MHA.shuffle(D.prepositions.filter(p=>p!==q.prep)).slice(0,2),MHA.shuffle(D.nouns.filter(n=>n!==q.noun))[0]]);const refresh=()=>{area.querySelectorAll('.orange-slot').forEach((slot,i)=>slot.textContent=z.words[i]||'___');$('orangeWords').querySelectorAll('button').forEach(b=>b.disabled=z.solved||z.words.includes(b.dataset.word))};bank.forEach(w=>{const b=button(w,()=>{if(z.solved||z.words.length===3||z.words.includes(w))return;$('feedback').textContent='';z.words.push(w);refresh();if(z.words.length===3){const correct=JSON.stringify(z.words)===JSON.stringify([q.prep,'the',q.noun]);answer(correct);if(!correct)z.words=[];refresh()}});b.dataset.word=w;$('orangeWords').append(b)})}
 }
 if(m.type==='final'){const choices=document.createElement('div');choices.className='choices';choices.style.flexDirection='column';MHA.makeFinalChoices(q).forEach(p=>choices.append(button(phrase(p),()=>answer(p.prep===q.prep&&p.noun===q.noun))));$('answerArea').append(choices)}
 function wordCards(){const selected=$('sentence'),cards=$('wordCards');selected.innerHTML='';cards.innerHTML='';z.words.forEach((w,i)=>selected.append(button(w,()=>{if(z.solved)return;z.words.splice(i,1);wordCards()})));z.order.filter(w=>!z.words.includes(w)).forEach(w=>cards.append(button(w,()=>{if(z.solved)return;z.words.push(w);wordCards()})))}
}
function answer(correct){if(!quiz||quiz.solved)return;if(!correct){$('feedback').textContent='Try again!';return}quiz.solved=true;$('feedback').textContent=['Correct!','Great job!','Excellent!','Well done!'][quiz.index%4];const a=$('quizActions');a.innerHTML='';a.append(button(quiz.index+1===quiz.mission.count?'Finish':'Next',()=>{if(quiz.index+1<quiz.mission.count){quiz.index++;renderQuiz()}else finishQuiz()},'primary'))}
function finishQuiz(){const m=quiz.mission;if(m.id==='final'){if(S.finish(gameState)){persist();ending()}else close();return}S.unlock(gameState,m.id);persist();dialogue(m,'TREASURE CHEST UNLOCKED!\nGo to the Treasure Room!',[['Back to the ship',close]]);quiz=null}
function setupDrag(c,q){let dragging=false,tapped=false;const point=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*600/r.width,y:(e.clientY-r.top)*280/r.height}};c.onpointerdown=e=>{if(quiz.solved)return;const p=point(e);if(tapped||Math.hypot(p.x-quiz.drag.x,p.y-quiz.drag.y)<60){dragging=true;tapped=true;c.setPointerCapture(e.pointerId);quiz.drag=p;scene(c,q,'gem_ruby',p,true)}e.preventDefault()};c.onpointermove=e=>{if(!dragging||quiz.solved)return;const p=point(e);quiz.drag={x:Math.max(30,Math.min(570,p.x)),y:Math.max(30,Math.min(250,p.y))};scene(c,q,'gem_ruby',quiz.drag,true)};c.onpointerup=e=>{if(!dragging)return;dragging=false;const p=quiz.drag;const nearest=Object.values(positions(q.noun)).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(Math.hypot(nearest.x-p.x,nearest.y-p.y)<48){quiz.drag={...nearest};tapped=false}scene(c,q,'gem_ruby',quiz.drag,true);if(c.hasPointerCapture(e.pointerId))c.releasePointerCapture(e.pointerId)};c.onpointercancel=()=>{dragging=false}}
// Keyboard, pointer, focus, and browser lifecycle.
const keyMap={w:'up',a:'left',s:'down',d:'right',arrowup:'up',arrowleft:'left',arrowdown:'down',arrowright:'right'};
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(keyMap[k]){if(mode==='world'){e.preventDefault();keys.add(keyMap[k])}return}if((k==='e'||k===' ')&&mode==='world'){e.preventDefault();if(!e.repeat)interaction()}if(e.key==='Escape'&&!['loading','opening','ending','complete','confirm'].includes(mode)){e.preventDefault();close()}if(e.key==='Tab'&&!overlay.hidden){const focusables=[...overlay.querySelectorAll('button:not(:disabled)')];const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
window.addEventListener('keyup',e=>keys.delete(keyMap[e.key.toLowerCase()]));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{keys.clear();if(document.hidden){stopSpeech();persist()}});window.addEventListener('pagehide',persist);
document.querySelectorAll('[data-dir]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();if(mode!=='world')return;b.setPointerCapture(e.pointerId);keys.add(b.dataset.dir)};const end=()=>keys.delete(b.dataset.dir);b.onpointerup=end;b.onpointercancel=end;b.onlostpointercapture=end});
 $('routeButton').onclick=()=>{if(mode==='world')playOrder()};$('interactButton').onclick=interaction;$('inventoryButton').onclick=()=>{if(mode==='world')inventory()};$('restartButton').onclick=()=>{if(mode!=='loading')restart()};$('soundButton').onclick=()=>{gameState.soundEnabled=!gameState.soundEnabled;stopSpeech();persist()};
 try{await A.load((n,total)=>$('loadingText').textContent=`Preparing Pirate World… ${n} / ${total}`);if(blocked(player.x,player.y))player={x:694,y:474};follower=companionStart();trail=[{...follower},{...player}];hud();requestAnimationFrame(frame);if(gameState.gameCompleted)completeScreen();else if(gameState.finalMissionCompleted)ending();else if(gameState.openingCompleted)close();else opening()}catch(err){$('loadingText').textContent=err.message+' — Please check the assets folder and reload.';console.error(err)}
 // Read-only diagnostics; tests can inspect state without adding gameplay cheat controls.
 MHA.inspect=()=>({state:JSON.parse(JSON.stringify(gameState)),player:{...player},follower:{...follower},nearest:nearest?.id||null,mode,quiz:quiz?{mission:quiz.mission.id,index:quiz.index,question:{...quiz.questions[quiz.index]},solved:quiz.solved,drag:{...quiz.drag},listenOptions:quiz.listenOptions}:null});
 MHA.geometry={blocked,inPolygon,positions};
 if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_adventure_progress',description:'Read gem, map and crew progress for this device. Does not reveal quiz answers or change progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('No arguments are accepted.');return{gems:gameState.gemsCollected.length,mapPieces:gameState.mapPieces,completedCrew:D.missions.filter(m=>gameState.completedChallenges[m.id]).map(m=>m.name),finalMissionUnlocked:gameState.finalMissionUnlocked,gameCompleted:gameState.gameCompleted}}})).catch(()=>{})}catch{}}
})();
